"""Compile the verified static FPGA scan into 320 ns GPIO samples for PIO/DMA."""
import argparse
import array
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CONFIG = (0x0000,0x0207,0x0335,0x0412,0x0500,0x0601,0x0720,0x0c18,
          0x0d01,0x0e86,0x0f01,0x1040,0x1127,0x1800,0x1906,0x1c60,
          0x1dca,0x1e73,0x2000,0x2100,0x2300,0x74a0)
CLOCK, LAT, OE = 1 << 9, 1 << 10, 1 << 11


def cycle(mask):
    return (mask, mask | CLOCK)


def initialization(config):
    result = []
    for length, high in ((16,3),(15,11),(24,14)):
        for count in range(length):
            result.extend(cycle(LAT if count < high else 0))
    for word in (0x00aa,0x01aa,config,0x0055,0x0155):
        for count in range(128):
            rgb = 63 if word & (1 << (15-count%16)) else 0
            result.extend(cycle(rgb | (LAT if count >= 123 else 0)))
    for _ in range(12):
        result.extend(cycle(OE))
    return result


def scanning(length, pattern=None, data=False):
    result = []
    row, phase = 0, 0
    for count in range(length):
        mask = row << 6
        if 100 <= phase < 104:
            mask |= OE
        if data and count%128 == 127:
            mask |= LAT
        if pattern is not None and count%16 == 7:
            mask |= pattern[count//16]
        result.extend(cycle(mask))
        if phase == 111:
            row = (row+1)%8
        phase = (phase+1)%128
    assert (row,phase) == (0,0)
    return result


def make_waves():
    pattern = [int(line,16) for line in (ROOT.parent/'panel'/'pattern.hex').read_text().split()]
    assert len(pattern) == 1024 and all(0 <= x < 64 for x in pattern)
    waves = {f'init_{index}': initialization(word) for index,word in enumerate(CONFIG)}
    waves.update(blank=scanning(1024,data=True), visible=scanning(16384,pattern,True),
                 hold=scanning(1024), gap=[0]*625)
    plan = []
    for frame in range(24):
        plan.append(f'init_{frame%22}')
        plan.extend(['blank']*16 if frame < 22 else ['visible'])
        if frame < 23:
            plan.extend(['hold']*32)
            plan.append('gap')
    plan.append('hold')
    return waves,plan


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--reference', type=Path, help='Binary high-SCLK samples from the original Verilog')
    args = ap.parse_args()
    waves,plan = make_waves()
    target = ROOT/'generated'
    target.mkdir(exist_ok=True)
    lines = ['// Generated by generate_wave.py. Mutable arrays are copied into SRAM at boot.',
             '#pragma once', '#include <stdint.h>', '#include <stddef.h>',
             'struct Wave { const uint16_t *samples; uint32_t count; };']
    for name,values in waves.items():
        lines.append(f'static uint16_t wave_{name}[] = {{')
        lines.extend('    '+','.join(f'0x{v:03x}' for v in values[i:i+16])+',' for i in range(0,len(values),16))
        lines.append('};')
    lines.append('static const Wave startup_plan[] = {')
    lines.extend(f'    {{wave_{name}, sizeof(wave_{name})/sizeof(uint16_t)}},' for name in plan)
    lines.extend(('};',f'static const size_t PLAN_COUNT = {len(plan)};'))
    (target/'wave_data.h').write_text('\n'.join(lines)+'\n',encoding='ascii')
    stats = dict(wave_bytes=sum(len(v)*2 for v in waves.values()),descriptors=len(plan),
                 descriptor_bytes=16*len(plan),startup_seconds=sum(len(waves[n]) for n in plan[:-1])*320e-9,
                 gpio_base=2,gpio_count=12,sample_ns=320,sclk_hz=1562500)
    (target/'wave-info.json').write_text(json.dumps(stats,indent=2),encoding='ascii')
    if args.reference:
        actual = array.array('H')
        with args.reference.open('rb') as source:
            actual.frombytes(source.read())
        if sys.byteorder != 'little':
            actual.byteswap()
        # The last hold sample is a repeating 1024-clock period.
        expected = array.array('H',(v for name in plan for v in waves[name] if v & CLOCK))
        if actual != expected:
            index = next((i for i,(a,b) in enumerate(zip(actual,expected)) if a != b),min(len(actual),len(expected)))
            raise AssertionError(f'FPGA/PIO mismatch at clock {index}, lengths {len(actual)}/{len(expected)}')
        print(f'PASS: {len(actual)} rising-clock GPIO samples exactly match original FPGA RTL')
    print(json.dumps(stats,indent=2))


if __name__ == '__main__':
    main()
